version: 2
updates:
  - package-ecosystem: pip
    directory: ./pyproject.toml
    schedule:
      interval: monthly
    target-branch: 'roiq-ai'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every week
      interval: monthly
