

services:

  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: owebui
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./ignore/data/pg_data/:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'


  open-webui:
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:
      - ./backend:/app/backend
    depends_on:
      - postgres
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    tty: true
    command: >
        bash -c "./dev.sh"
    env_file:
      - .env

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "9595:9595"
    volumes:
      - ./ignore/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
      - ALLOW_RESET=TRUE
    stdin_open: true
    tty: true
    command: "--workers 1 --host 0.0.0.0 --port 9595 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    healthcheck:
      # Adjust below to match your container port
      test: [ "CMD", "curl", "-f", "http://localhost:9595/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3

  pipelines:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: ghcr.io/open-webui/pipelines:main
    ports:
      - "9099:9099"
    volumes:
      - ./ignore/pipelines:/app/pipelines/
    env_file:
      - .env
    stdin_open: true
    restart: always

volumes:
  ollama: {}
  open-webui: {}
