services:



  postgres:
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: adsrc
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./ignore/data/pg_data/:/var/lib/postgresql/data
    command: postgres -c 'max_connections=1000'

  chroma:
    image: chromadb/chroma:0.5.15
    ports:
      - "9595:9595"
    volumes:
      - ./ignore/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
      - ALLOW_RESET=TRUE
    stdin_open: true
    tty: true
    command: "--workers 1 --host 0.0.0.0 --port 9595 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    healthcheck:
      # Adjust below to match your container port
      test: [ "CMD", "curl", "-f", "http://localhost:9595/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3


  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'

      dockerfile: Dockerfile
    env_file:
      - ./ignore/envfile.env
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    platform: linux/amd64
    container_name: open-webui
    volumes:
      - ./ignore/open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}
