services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    command: >
        bash -c "alembic upgrade head && ./dev.sh"
    env_file:
      - .env

  chroma:
    image: chromadb/chroma:latest
    ports:
      - "9595:9595"
    volumes:
      - ./ignore/chroma:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=${PERSIST_DIRECTORY:-/chroma/chroma}
      - ALLOW_RESET=TRUE
    stdin_open: true
    tty: true
    command: "--workers 1 --host 0.0.0.0 --port 9595 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    healthcheck:
      # Adjust below to match your container port
      test: [ "CMD", "curl", "-f", "http://localhost:9595/api/v1/heartbeat" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama: {}
  open-webui: {}
