"""add user_mapping

Revision ID: f622d7777d61
Revises: 7e5b5dc7342b
Create Date: 2024-09-17 09:55:39.668086

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import open_webui.apps.webui.internal.db


# revision identifiers, used by Alembic.
revision: str = "f622d7777d61"
down_revision: Union[str, None] = "7e5b5dc7342b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    from open_webui.migrations.util import get_existing_tables

    existing_tables = set(get_existing_tables())
    if "username_mapping" not in existing_tables:
        op.create_table(
            "username_mapping",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True),
            sa.Column("account_id", sa.VARCHAR(), autoincrement=False, nullable=True),
            sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
            sa.Column("daterange", sa.VARCHAR(), autoincrement=False, nullable=True),
            sa.PrimaryKeyConstraint("id", name="username_mapping_pkey"),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("username_mapping")
    # ### end Alembic commands ###
