"""init

Revision ID: b0e868a5ed87
Revises:
Create Date: 2024-08-23 13:05:38.249858

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0e868a5ed87"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("migratehistory")
    op.alter_column(
        "auth", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("auth", "password", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "auth", "active", existing_type=sa.INTEGER(), type_=sa.Boolean(), nullable=True
    )
    op.drop_index("auth_id", table_name="auth")
    op.alter_column(
        "chat", "user_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("chat", "title", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("chat", "chat", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "chat",
        "created_at",
        existing_type=sa.DATETIME(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.alter_column(
        "chat",
        "updated_at",
        existing_type=sa.DATETIME(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.alter_column(
        "chat",
        "share_id",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "chat",
        "archived",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        nullable=True,
    )
    op.drop_index("chat_id", table_name="chat")
    op.drop_index("chat_share_id", table_name="chat")
    op.create_unique_constraint(None, "chat", ["share_id"])
    op.alter_column(
        "chatidtag", "tag_name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "chatidtag", "chat_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "chatidtag", "user_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "chatidtag",
        "timestamp",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.drop_index("chatidtag_id", table_name="chatidtag")
    op.alter_column(
        "document", "name", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("document", "title", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("document", "filename", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "document", "user_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "document",
        "timestamp",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.drop_index("document_collection_name", table_name="document")
    op.drop_index("document_name", table_name="document")
    op.create_unique_constraint(None, "document", ["name"])
    op.drop_column("document", "id")
    op.alter_column(
        "file",
        "id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "file", "user_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=True
    )
    op.alter_column("file", "filename", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("file", "meta", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "file",
        "created_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.drop_index("file_id", table_name="file")
    op.alter_column(
        "function",
        "id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "function", "user_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=True
    )
    op.alter_column("function", "name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("function", "type", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("function", "content", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("function", "meta", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "function",
        "is_active",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        nullable=True,
    )
    op.alter_column(
        "function",
        "is_global",
        existing_type=sa.INTEGER(),
        type_=sa.Boolean(),
        nullable=True,
    )
    op.alter_column(
        "function",
        "updated_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.alter_column(
        "function",
        "created_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.drop_index("function_id", table_name="function")
    op.alter_column(
        "memory", "user_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("memory", "content", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "memory",
        "updated_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.alter_column(
        "memory",
        "created_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.drop_index("memory_id", table_name="memory")
    op.alter_column("model", "user_id", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("model", "name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("model", "params", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("model", "meta", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "model",
        "updated_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.alter_column(
        "model",
        "created_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.drop_index("model_id", table_name="model")
    op.alter_column(
        "prompt", "user_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("prompt", "title", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("prompt", "content", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "prompt",
        "timestamp",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.drop_index("prompt_command", table_name="prompt")
    op.drop_column("prompt", "id")
    op.alter_column("tag", "name", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column(
        "tag", "user_id", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_index("tag_id", table_name="tag")
    op.alter_column(
        "tool",
        "id",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "tool", "user_id", existing_type=sa.TEXT(), type_=sa.String(), nullable=True
    )
    op.alter_column("tool", "name", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("tool", "content", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("tool", "specs", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("tool", "meta", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "tool",
        "updated_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.alter_column(
        "tool",
        "created_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.drop_index("tool_id", table_name="tool")
    op.alter_column("user", "name", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column("user", "role", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("user", "profile_image_url", existing_type=sa.TEXT(), nullable=True)
    op.alter_column(
        "user",
        "last_active_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.alter_column(
        "user",
        "updated_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.alter_column(
        "user",
        "created_at",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        nullable=True,
    )
    op.drop_index("user_api_key", table_name="user")
    op.drop_index("user_id", table_name="user")
    op.drop_index("user_oauth_sub", table_name="user")
    op.create_unique_constraint(None, "user", ["api_key"])
    op.create_unique_constraint(None, "user", ["oauth_sub"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.create_index("user_oauth_sub", "user", ["oauth_sub"], unique=1)
    op.create_index("user_id", "user", ["id"], unique=1)
    op.create_index("user_api_key", "user", ["api_key"], unique=1)
    op.alter_column(
        "user",
        "created_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "user",
        "updated_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "user",
        "last_active_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "user", "profile_image_url", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "user", "role", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "user", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "user", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.create_index("tool_id", "tool", ["id"], unique=1)
    op.alter_column(
        "tool",
        "created_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "tool",
        "updated_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column("tool", "meta", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("tool", "specs", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("tool", "content", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("tool", "name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "tool", "user_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "tool",
        "id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_index("tag_id", "tag", ["id"], unique=1)
    op.alter_column(
        "tag", "user_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("tag", "name", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.add_column("prompt", sa.Column("id", sa.INTEGER(), nullable=False))
    op.create_index("prompt_command", "prompt", ["command"], unique=1)
    op.alter_column(
        "prompt",
        "timestamp",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column("prompt", "content", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("prompt", "title", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "prompt", "user_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.create_index("model_id", "model", ["id"], unique=1)
    op.alter_column(
        "model",
        "created_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "model",
        "updated_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column("model", "meta", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("model", "params", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("model", "name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("model", "user_id", existing_type=sa.TEXT(), nullable=False)
    op.create_index("memory_id", "memory", ["id"], unique=1)
    op.alter_column(
        "memory",
        "created_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "memory",
        "updated_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column("memory", "content", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "memory", "user_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.create_index("function_id", "function", ["id"], unique=1)
    op.alter_column(
        "function",
        "created_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "function",
        "updated_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "function",
        "is_global",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "function",
        "is_active",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column("function", "meta", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("function", "content", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("function", "type", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("function", "name", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "function",
        "user_id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        nullable=False,
    )
    op.alter_column(
        "function",
        "id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_index("file_id", "file", ["id"], unique=1)
    op.alter_column(
        "file",
        "created_at",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column("file", "meta", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("file", "filename", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "file", "user_id", existing_type=sa.String(), type_=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "file",
        "id",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.add_column("document", sa.Column("id", sa.INTEGER(), nullable=False))
    op.drop_constraint(None, "document", type_="unique")
    op.create_index("document_name", "document", ["name"], unique=1)
    op.create_index(
        "document_collection_name", "document", ["collection_name"], unique=1
    )
    op.alter_column(
        "document",
        "timestamp",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "document", "user_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column("document", "filename", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("document", "title", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "document", "name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.create_index("chatidtag_id", "chatidtag", ["id"], unique=1)
    op.alter_column(
        "chatidtag",
        "timestamp",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "chatidtag", "user_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "chatidtag", "chat_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.alter_column(
        "chatidtag", "tag_name", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_constraint(None, "chat", type_="unique")
    op.create_index("chat_share_id", "chat", ["share_id"], unique=1)
    op.create_index("chat_id", "chat", ["id"], unique=1)
    op.alter_column(
        "chat",
        "archived",
        existing_type=sa.Boolean(),
        type_=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "chat",
        "share_id",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "chat",
        "updated_at",
        existing_type=sa.BigInteger(),
        type_=sa.DATETIME(),
        nullable=False,
    )
    op.alter_column(
        "chat",
        "created_at",
        existing_type=sa.BigInteger(),
        type_=sa.DATETIME(),
        nullable=False,
    )
    op.alter_column("chat", "chat", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("chat", "title", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "chat", "user_id", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.create_index("auth_id", "auth", ["id"], unique=1)
    op.alter_column(
        "auth", "active", existing_type=sa.Boolean(), type_=sa.INTEGER(), nullable=False
    )
    op.alter_column("auth", "password", existing_type=sa.TEXT(), nullable=False)
    op.alter_column(
        "auth", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.create_table(
        "migratehistory",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=255), nullable=False),
        sa.Column("migrated_at", sa.DATETIME(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
