name: Build and Push to ECR

on:
  push:
    branches:
      - roiq-main

permissions:  write-all

env:
  REPOSITORY: 875668830489.dkr.ecr.us-east-1.amazonaws.com/roiqai-service

jobs:
  build-and-push-image:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4 # More information on this action can be found below in the 'AWS Credentials' section
      with:
        role-to-assume: arn:aws:iam::875668830489:role/GithubActionsRole
        aws-region: us-east-1
        audience: sts.amazonaws.com
    - name: Bump Version
      id: get_version
      run: |
        echo "Bumping version"
        export RYE_INSTALL_OPTION="--yes"
        curl -sSf https://rye.astral.sh/get  | bash
        source "$HOME/.rye/env"
        rye version -b minor
        echo Version: $(rye version)
        echo "VERSION=$(rye version)" >> $GITHUB_OUTPUT


    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Create and use a new builder instance
      run: |
        docker buildx create --name builder --use

    - name: Build and push
      uses: docker/build-push-action@v5
      env:
        IMAGE_TAG: ${{ steps.get_version.outputs.VERSION }}

      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{env.REPOSITORY}}:${{env.IMAGE_TAG}}
        builder: builder
        cache-from: type=registry,ref=${{env.REPOSITORY}}:cache
        cache-to: type=registry,mode=max,image-manifest=true,oci-mediatypes=true,ref=${{env.REPOSITORY}}:cache

    - name: Push commit
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -am "minor: Bump release version to ${{ steps.get_version.VERSION }}"
        git push